//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amonicAirlines
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shadowing
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan LogIn { get; set; }
        public System.TimeSpan LogOut { get; set; }
        public System.TimeSpan TimeSpent { get; set; }
        public int Crashes { get; set; }
        public string CrashReason { get; set; }
        public int UserID { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
